### PR TITLE
Escaping distinguished names functionality

### PR DESCRIPTION
**Pull request by adrianplavka**
This branch resolved [#2](https://github.com/ldapts/ldapts/issues/2) issue with escaping DN's.

I've closely implemented this by looking at RFC specification, which defines, how DN strings should be escaped. I've also added some basic tests, that cover these cases.

The `DNMap` type is basically a list, that contains lists of pairs ('key' & 'value'). The escaping is done by iterating over them & applying escaping to every value. After that, the function returns a string representation of the DN.

The problem I've encountered with the new `DNMap` type is an interesting one. I wanted to implement this as an object, but after realizing, that DN can contain multiple existing keys (for example, multiple 'dc' keys), I've made the decision of it being a list of lists, basically.

A basic example of usage looks like this:
```javascript
import * as ldap from 'ldapts';

// ...
const baseDN: ldap.DNMap = [['email', account.email], ['dc', env.ldap.organisation], ['dc', env.ldap.domain]];

await this.client.add(baseDN, entry);
```

Client was reworked, in which he can now accept a `DNMap` type of a DN. In order to maintain backwards compatibility, DN's can also be passed as strings, but they will NOT get escaped.

I didn't modify README with this update, I'll leave that to you. But I think it's necessary to notice other users, that this method of providing a DN should be, in most cases, a must.

### CODE REVIEW

**Comment by adrianplavka** [comment]
@jgeurts

**Comment by adrianplavka** [comment]
After a couple of thoughts, I've added a new `DNBuilder` class, which can chain multiple RDN components to build an escaped string representation of a DN. 

An example usage would be like:
```javascript
import * as ldap from 'ldapts';

// ...
const baseDN = new DNBuilder()
    .addRDN('email', account.email)
    .addRDN('dc', env.ldap.organisation)
    .addRDN('dc', env.ldap.domain)
    .build();

await this.client.add(baseDN, entry);
```

The API didn't change, but this should give a user to have a better building process (this targets users, who like to chain methods in order to build an SQL query, for example).

Client now uses this builder to escape `DNMap` types & I've also included additional test for this new class.

**Comment by jgeurts** [comment]
I've been thinking about porting over the [DN class from ldapjs](https://github.com/joyent/node-ldapjs/blob/master/lib/dn.js). Think that could work in conjunction with the DNBuilder?

**Comment by adrianplavka** [comment]
I've looked at it and I think it could, let me see what I can come up with.

**Comment by adrianplavka** [comment]
@jgeurts Sorry that it took so long.

I've re-implemented the DN class, which acts as a builder itself, accepting variety of objects & interfaces. I've also added RDN class, which under the hood escapes values. It's been done by working closely with the `ldapjs` DN class you've posted earlier.

The RDN class accepts compound attributes, meaning that one RDN can consist of multiple key & value pairs.

Of course, tests were added as well. Let me know what you think of the current API!

**Comment by adrianplavka** [comment]
I've updated `DNAttributes` interface, that now accepts list of strings. The problem was, when a DN had multiple values with the same key.

Take a look at an example:
```typescript
const bindDN = new DN({
    uid: 'tony.stark',
    ou: 'Users',
    o: '5be4c382c583e54de6a3ff52',
    dc: 'jumpcloud',
  }).add({ dc: 'com' }).toString();
```

You had to add a separate chain call, that would append it with the same key.

With the updated API, it now looks like:
```typescript
const bindDN = new DN({
    uid: 'tony.stark',
    ou: 'Users',
    o: '5be4c382c583e54de6a3ff52',
    dc: ['jumpcloud', 'com'],
  }).toString();
```

**Comment by jgeurts** [comment]
This looks awesome, thank you!

**Pull request merged**
