### PR TITLE
Allow for optional password by setting a default empty string

### PR DESCRIPTION
**Pull request by wattry**

### CODE REVIEW

**Comment by TimoHocker** [comment]
the other changes in [my commit](https://github.com/ldapts/ldapts/commit/41da44f4a268ad6d7f2805f2ecd1774ceeb3b935) should also be reverted since they are then unnecessary.

**Comment by thernstig** [comment]
Works fine, but will await to "LGTM" till @TimoHocker's comment has been addressed.

**Comment by TimoHocker** [comment]
It could be a number or some random object if the user of this library decides to not use typescript and ignores the warnings. but even then it should probably be checked once in the constructor and not in multiple different places. If you chose to ignore parameters that are not strings it could cause another problem to someone who passes numbers for whatever reason.

Id prefer that either the commit gets completely reverted or that the type is checked once in the constructor and rejected with an error so nobody has to search long through endless amounts of code to find out why their password is not passed along.

**Comment by TimoHocker** [comment]
Except that tsc is not happy about the optional password field in BindRequest. That's the last change that needs to be reverted.
Guess a `git revert 41da44f` would have done the job too 😜
Anyways, I'm happy with the pull request now.

**Comment by TimoHocker** [comment]
I don't know what the writeString function does exactly, but if it stays true to its name, then it would probably throw an error if the controls slip into the password field. 

The options object is a great idea, but probably worth a new pullrequest/issue for discussion.

Anyways, here is the result of a fresh clone of your repository, installing modules and running tsc:
```cmd
c:\dev\ldapts>npm run build

> ldapts@4.2.6 build
> tsc

src/messages/BindRequest.ts:42:26 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

42       writer.writeString(this.password);
                            ~~~~~~~~~~~~~

src/messages/BindRequest.ts:47:26 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

47       writer.writeString(this.password, Ber.Context); // 128
                            ~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/messages/BindRequest.ts:42
```

**Comment by TimoHocker** [comment]
I can reproduce it in a clean node:lts docker container

```sh
root@972c4b37d235:/# git clone https://github.com/ldapts/ldapts.git
...
root@972c4b37d235:/ldapts# git fetch origin pull/134/head:wattry
 * [new ref]         refs/pull/134/head -> wattry
root@972c4b37d235:/ldapts# git checkout wattry
...
root@972c4b37d235:/ldapts# npm i
...
root@972c4b37d235:/ldapts# npm run build
```

same error, this time I checked out the pull request directly
but the same happens with `git clone https://github.com/wattry/ldapts.git --branch wattry`

**Comment by thernstig** [comment]
Thanks! Hope @jgeurts can merge when he has some downtime.

**Comment by jgeurts** [comment]
Thanks all! My apologies on timing for getting this merged in. The company I worked for was acquired and that kind of flipped my world upside down. I'll take a look and get this merged in over the next week. Thanks again!

**Pull request merged**
