### PR TITLE
Allow more SASL mechanisms like DIGEST-MD5 and SCRAM-SHA-1

### PR DESCRIPTION
**Pull request by TimoHocker**
With this pull request I have expanded the auto detection feature for SASL mechanisms and added a second function that allows SASL binds with any other mechanism that is not included in the list.

The bind response will also parse additional data, this allows reading the server's challenges for the challenge response type mechanisms.

Lastly I have noticed a warning about the packet being malformed on the initial request to the ldap server when using DIGEST-MD5. The password field should not be sent if it is not used.

### CODE REVIEW

**Comment by jgeurts** [comment]
Thanks @TimoHocker!

@wattry or @thernstig Would either of you be able to check things still work for you with these changes? #89 had some issues with blank/missing passwords, I believe. Let me know if you want me to push a beta npm, if that makes verifying easier.

**Comment by wattry** [comment]
> Thanks @TimoHocker!
> 
> @wattry or @thernstig Would either of you be able to check things still work for you with these changes? #89 had some issues with blank/missing passwords, I believe. Let me know if you want me to push a beta npm, if that makes verifying easier.

@jgeurts apologies, just seeing this now. 

I installed the PR branch locally and ran it against my current setup and I was able to connect to the LDAP server. I think just to be safe. Please push up a beta npm version so I can install it in my dependencies to double check. Thanks for the heads up

**Comment by jgeurts** [comment]
@wattry Could you please give [v4.2.0-beta1](https://www.npmjs.com/package/ldapts/v/4.2.0-beta) a shot when you have a chance? Thanks!

**Comment by wattry** [comment]
Weirdly, I'm getting this when I try install that version, however, I verified it exists in [npm](https://www.npmjs.com/package/ldapts/v/4.2.0-beta). 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ldapts@4.2.0-beta.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by TimoHocker** [comment]
`$ npm i ldapts@4.2.0-beta
added 10 packages, and audited 11 packages in 5s`

works fine here, are you possibly using a different registry or caching proxy?

**Comment by jgeurts** [comment]
@wattry It might have been my bad... there is no `1` at the end of the npm name. Using the command that @TimoHocker mentioned should work to install the package.

**Comment by jgeurts** [comment]
Going to merge this and if there are problems, they can be addressed in a separate PR. Thank you @TimoHocker for the contribution!

**Comment by wattry** [comment]
> Going to merge this and if there are problems, they can be addressed in a separate PR. Thank you @TimoHocker for the contribution!

@jgeurts, apologies I've been unwell. We haven't updated our version and likely won't since we don't require the new functionality so that approach makes sense. Good work @TimoHocker!

**Comment by wattry** [comment]
Confirmed that it still works with the new version.

**Comment by jgeurts** [comment]
Awesome, thanks for letting us know!

**Pull request merged**
