### PR TITLE
Added test for parens in search filters 

### PR DESCRIPTION
**Pull request by stiller-leser**
Went full 
grafik
and created a test for #18. I am not sure if the DN for the search is correct of if it is the right return value to expect, but I am happy to adjust this.

Currently it returns no result (just like in my case).

### CODE REVIEW

**Comment by jgeurts** [comment]
I tweaked your example slightly with:

```js
      // NOTE: ldapsearch -H ldaps://ldap.jumpcloud.com -b o=5be4c382c583e54de6a3ff52,dc=jumpcloud,dc=com -x -D uid=tony.stark,ou=Users,o=5be4c382c583e54de6a3ff52,dc=jumpcloud,dc=com -w MyRedSuitKeepsMeWarm "(&(objectClass=groupOfNames)(cn=Something \28Special\29))"
      const filter: AndFilter = new AndFilter({
        filters: [
          new EqualityFilter({
            attribute: 'objectClass',
            value: 'groupOfNames',
          }),
          new EqualityFilter({
            attribute: 'cn',
            value: 'Something (Special)',
          }),
        ],
      });
```

That provides a working ldapsearch command and equivalent filters. It seems to reproduce the problem, which is bitter sweet :)

**Comment by jgeurts** [comment]
I'll likely add another test for the string version, too, just to cover my bases:
```
    it('should return group contents - string filter', async () => {
      // NOTE: ldapsearch -H ldaps://ldap.jumpcloud.com -b o=5be4c382c583e54de6a3ff52,dc=jumpcloud,dc=com -x -D uid=tony.stark,ou=Users,o=5be4c382c583e54de6a3ff52,dc=jumpcloud,dc=com -w MyRedSuitKeepsMeWarm "(&(objectClass=groupOfNames)(cn=Something \28Special\29))"
      const searchResult = await client.search('o=5be4c382c583e54de6a3ff52,dc=jumpcloud,dc=com', {
        filter: '(&(objectClass=groupOfNames)(cn=Something \\28Special\\29))',
      });
```

**Comment by stiller-leser** [comment]
Hi,

I keep being amazed by how responsive you are. Kudos for this! I'm glad that you were able to reproduce the issue (if you know what I mean ;)).

Let me know if any other action from my side is needed.

**Comment by jgeurts** [comment]
Thanks for this test - I have added it to the `Client.tests.ts` file as of v1.6.0

**Pull request closed without merging**
